version: '3.8'

services:
  db_transport_app:
    image: postgres
    container_name: db_transport_app
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
